# Project Euler Problem 2 Description

# Each new term in the Fibonacci sequence is generated by adding the previous
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.


def sum_of_evens(limit)

	previous, current, start_evens_sum = [0, 1, 0]
	sequence(previous, current, start_evens_sum, limit)

end

def sequence(previous, current, evens_sum, limit)

	return evens_sum if current >= limit
	sum = previous + current
	sum % 2 == 0 ? new_sum = evens_sum + sum : new_sum = evens_sum
	sequence(current, sum, new_sum, limit)

end

# Tracks time
start = Time.now
puts sum_of_evens(4000000)
puts "Execution time: #{Time.now - start}"

# Answer: 4613732
# Time Elasped: 0.000048
